spring:
  application:
    name: assignment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: assignment_user
    password: assignment_password
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082
